name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  license-check:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pip-licenses
      - name: Run license-check
        run: > 
          pip-licenses
          --allow-only="
            Apache Software License;
            BSD License;
            Freely Distributable;
            MIT License;
            Mozilla Public License 2.0 (MPL 2.0);
          "

  flake8:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install flake8
      - name: Run Flake8
        run: flake8

  tests:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest
      - name: Run tests
        run: python -m pytest
